// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: presence/v1/presence.proto

package presencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserStatus int32

const (
	UserStatus_USER_STATUS_UNSPECIFIED UserStatus = 0
	UserStatus_USER_STATUS_ONLINE      UserStatus = 1
	UserStatus_USER_STATUS_IDLE        UserStatus = 2
	UserStatus_USER_STATUS_DND         UserStatus = 3
	UserStatus_USER_STATUS_OFFLINE     UserStatus = 4
)

// Enum value maps for UserStatus.
var (
	UserStatus_name = map[int32]string{
		0: "USER_STATUS_UNSPECIFIED",
		1: "USER_STATUS_ONLINE",
		2: "USER_STATUS_IDLE",
		3: "USER_STATUS_DND",
		4: "USER_STATUS_OFFLINE",
	}
	UserStatus_value = map[string]int32{
		"USER_STATUS_UNSPECIFIED": 0,
		"USER_STATUS_ONLINE":      1,
		"USER_STATUS_IDLE":        2,
		"USER_STATUS_DND":         3,
		"USER_STATUS_OFFLINE":     4,
	}
)

func (x UserStatus) Enum() *UserStatus {
	p := new(UserStatus)
	*p = x
	return p
}

func (x UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_presence_v1_presence_proto_enumTypes[0].Descriptor()
}

func (UserStatus) Type() protoreflect.EnumType {
	return &file_presence_v1_presence_proto_enumTypes[0]
}

func (x UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserStatus.Descriptor instead.
func (UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

type Presence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=presence.v1.UserStatus" json:"status,omitempty"`
	CustomStatus  string                 `protobuf:"bytes,3,opt,name=custom_status,json=customStatus,proto3" json:"custom_status,omitempty"`
	LastActiveAt  int64                  `protobuf:"varint,4,opt,name=last_active_at,json=lastActiveAt,proto3" json:"last_active_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{0}
}

func (x *Presence) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Presence) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *Presence) GetCustomStatus() string {
	if x != nil {
		return x.CustomStatus
	}
	return ""
}

func (x *Presence) GetLastActiveAt() int64 {
	if x != nil {
		return x.LastActiveAt
	}
	return 0
}

type SetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        UserStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=presence.v1.UserStatus" json:"status,omitempty"`
	StatusInfo    string                 `protobuf:"bytes,3,opt,name=status_info,json=statusInfo,proto3" json:"status_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusRequest) Reset() {
	*x = SetStatusRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusRequest) ProtoMessage() {}

func (x *SetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusRequest.ProtoReflect.Descriptor instead.
func (*SetStatusRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{1}
}

func (x *SetStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetStatusRequest) GetStatus() UserStatus {
	if x != nil {
		return x.Status
	}
	return UserStatus_USER_STATUS_UNSPECIFIED
}

func (x *SetStatusRequest) GetStatusInfo() string {
	if x != nil {
		return x.StatusInfo
	}
	return ""
}

type SetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStatusResponse) Reset() {
	*x = SetStatusResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStatusResponse) ProtoMessage() {}

func (x *SetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStatusResponse.ProtoReflect.Descriptor instead.
func (*SetStatusResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{2}
}

func (x *SetStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetUserStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatusesRequest) Reset() {
	*x = GetUserStatusesRequest{}
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatusesRequest) ProtoMessage() {}

func (x *GetUserStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatusesRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatusesRequest) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatusesRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type GetUserStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      map[string]*Presence   `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserStatusesResponse) Reset() {
	*x = GetUserStatusesResponse{}
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatusesResponse) ProtoMessage() {}

func (x *GetUserStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_presence_v1_presence_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatusesResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatusesResponse) Descriptor() ([]byte, []int) {
	return file_presence_v1_presence_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStatusesResponse) GetStatuses() map[string]*Presence {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_presence_v1_presence_proto protoreflect.FileDescriptor

const file_presence_v1_presence_proto_rawDesc = "" +
	"\n" +
	"\x1apresence/v1/presence.proto\x12\vpresence.v1\"\x9f\x01\n" +
	"\bPresence\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.presence.v1.UserStatusR\x06status\x12#\n" +
	"\rcustom_status\x18\x03 \x01(\tR\fcustomStatus\x12$\n" +
	"\x0elast_active_at\x18\x04 \x01(\x03R\flastActiveAt\"}\n" +
	"\x10SetStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12/\n" +
	"\x06status\x18\x02 \x01(\x0e2\x17.presence.v1.UserStatusR\x06status\x12\x1f\n" +
	"\vstatus_info\x18\x03 \x01(\tR\n" +
	"statusInfo\"-\n" +
	"\x11SetStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x16GetUserStatusesRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xbd\x01\n" +
	"\x17GetUserStatusesResponse\x12N\n" +
	"\bstatuses\x18\x01 \x03(\v22.presence.v1.GetUserStatusesResponse.StatusesEntryR\bstatuses\x1aR\n" +
	"\rStatusesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.presence.v1.PresenceR\x05value:\x028\x01*\x85\x01\n" +
	"\n" +
	"UserStatus\x12\x1b\n" +
	"\x17USER_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12USER_STATUS_ONLINE\x10\x01\x12\x14\n" +
	"\x10USER_STATUS_IDLE\x10\x02\x12\x13\n" +
	"\x0fUSER_STATUS_DND\x10\x03\x12\x17\n" +
	"\x13USER_STATUS_OFFLINE\x10\x042\xbb\x01\n" +
	"\x0fPresenceService\x12J\n" +
	"\tSetStatus\x12\x1d.presence.v1.SetStatusRequest\x1a\x1e.presence.v1.SetStatusResponse\x12\\\n" +
	"\x0fGetUserStatuses\x12#.presence.v1.GetUserStatusesRequest\x1a$.presence.v1.GetUserStatusesResponseBBZ@github.com/sudo-odner/minor-shared/pkg/pb/presence/v1;presencev1b\x06proto3"

var (
	file_presence_v1_presence_proto_rawDescOnce sync.Once
	file_presence_v1_presence_proto_rawDescData []byte
)

func file_presence_v1_presence_proto_rawDescGZIP() []byte {
	file_presence_v1_presence_proto_rawDescOnce.Do(func() {
		file_presence_v1_presence_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)))
	})
	return file_presence_v1_presence_proto_rawDescData
}

var file_presence_v1_presence_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_presence_v1_presence_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_presence_v1_presence_proto_goTypes = []any{
	(UserStatus)(0),                 // 0: presence.v1.UserStatus
	(*Presence)(nil),                // 1: presence.v1.Presence
	(*SetStatusRequest)(nil),        // 2: presence.v1.SetStatusRequest
	(*SetStatusResponse)(nil),       // 3: presence.v1.SetStatusResponse
	(*GetUserStatusesRequest)(nil),  // 4: presence.v1.GetUserStatusesRequest
	(*GetUserStatusesResponse)(nil), // 5: presence.v1.GetUserStatusesResponse
	nil,                             // 6: presence.v1.GetUserStatusesResponse.StatusesEntry
}
var file_presence_v1_presence_proto_depIdxs = []int32{
	0, // 0: presence.v1.Presence.status:type_name -> presence.v1.UserStatus
	0, // 1: presence.v1.SetStatusRequest.status:type_name -> presence.v1.UserStatus
	6, // 2: presence.v1.GetUserStatusesResponse.statuses:type_name -> presence.v1.GetUserStatusesResponse.StatusesEntry
	1, // 3: presence.v1.GetUserStatusesResponse.StatusesEntry.value:type_name -> presence.v1.Presence
	2, // 4: presence.v1.PresenceService.SetStatus:input_type -> presence.v1.SetStatusRequest
	4, // 5: presence.v1.PresenceService.GetUserStatuses:input_type -> presence.v1.GetUserStatusesRequest
	3, // 6: presence.v1.PresenceService.SetStatus:output_type -> presence.v1.SetStatusResponse
	5, // 7: presence.v1.PresenceService.GetUserStatuses:output_type -> presence.v1.GetUserStatusesResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_presence_v1_presence_proto_init() }
func file_presence_v1_presence_proto_init() {
	if File_presence_v1_presence_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_presence_v1_presence_proto_rawDesc), len(file_presence_v1_presence_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_presence_v1_presence_proto_goTypes,
		DependencyIndexes: file_presence_v1_presence_proto_depIdxs,
		EnumInfos:         file_presence_v1_presence_proto_enumTypes,
		MessageInfos:      file_presence_v1_presence_proto_msgTypes,
	}.Build()
	File_presence_v1_presence_proto = out.File
	file_presence_v1_presence_proto_goTypes = nil
	file_presence_v1_presence_proto_depIdxs = nil
}
