// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.6
// source: community/v1/community.proto

package communityv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
}

func (x *FetchPermissionRequest) Reset() {
	*x = FetchPermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_community_v1_community_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionRequest) ProtoMessage() {}

func (x *FetchPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionRequest.ProtoReflect.Descriptor instead.
func (*FetchPermissionRequest) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchPermissionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type FetchPermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PermissionMask uint64 `protobuf:"varint,1,opt,name=permission_mask,json=permissionMask,proto3" json:"permission_mask,omitempty"`
}

func (x *FetchPermissionResponse) Reset() {
	*x = FetchPermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_community_v1_community_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FetchPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionResponse) ProtoMessage() {}

func (x *FetchPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_v1_community_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionResponse.ProtoReflect.Descriptor instead.
func (*FetchPermissionResponse) Descriptor() ([]byte, []int) {
	return file_community_v1_community_proto_rawDescGZIP(), []int{1}
}

func (x *FetchPermissionResponse) GetPermissionMask() uint64 {
	if x != nil {
		return x.PermissionMask
	}
	return 0
}

var File_community_v1_community_proto protoreflect.FileDescriptor

var file_community_v1_community_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31, 0x2f, 0x63,
	0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x22, 0x50, 0x0a, 0x16,
	0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x42,
	0x0a, 0x17, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x65, 0x72,
	0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0e, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x4d, 0x61,
	0x73, 0x6b, 0x32, 0x72, 0x0a, 0x10, 0x43, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5e, 0x0a, 0x0f, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50,
	0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x74, 0x63, 0x68, 0x50, 0x65,
	0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x25, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x31, 0x2e, 0x46,
	0x65, 0x74, 0x63, 0x68, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x44, 0x5a, 0x42, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x75, 0x64, 0x6f, 0x2d, 0x6f, 0x64, 0x6e, 0x65, 0x72, 0x2f,
	0x6d, 0x69, 0x6e, 0x6f, 0x72, 0x2d, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x2f, 0x70, 0x6b, 0x67,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x2f, 0x76, 0x31,
	0x3b, 0x63, 0x6f, 0x6d, 0x6d, 0x75, 0x6e, 0x69, 0x74, 0x79, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_community_v1_community_proto_rawDescOnce sync.Once
	file_community_v1_community_proto_rawDescData = file_community_v1_community_proto_rawDesc
)

func file_community_v1_community_proto_rawDescGZIP() []byte {
	file_community_v1_community_proto_rawDescOnce.Do(func() {
		file_community_v1_community_proto_rawDescData = protoimpl.X.CompressGZIP(file_community_v1_community_proto_rawDescData)
	})
	return file_community_v1_community_proto_rawDescData
}

var file_community_v1_community_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_community_v1_community_proto_goTypes = []interface{}{
	(*FetchPermissionRequest)(nil),  // 0: community.v1.FetchPermissionRequest
	(*FetchPermissionResponse)(nil), // 1: community.v1.FetchPermissionResponse
}
var file_community_v1_community_proto_depIdxs = []int32{
	0, // 0: community.v1.CommunityService.FetchPermission:input_type -> community.v1.FetchPermissionRequest
	1, // 1: community.v1.CommunityService.FetchPermission:output_type -> community.v1.FetchPermissionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_community_v1_community_proto_init() }
func file_community_v1_community_proto_init() {
	if File_community_v1_community_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_community_v1_community_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_community_v1_community_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FetchPermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_community_v1_community_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_v1_community_proto_goTypes,
		DependencyIndexes: file_community_v1_community_proto_depIdxs,
		MessageInfos:      file_community_v1_community_proto_msgTypes,
	}.Build()
	File_community_v1_community_proto = out.File
	file_community_v1_community_proto_rawDesc = nil
	file_community_v1_community_proto_goTypes = nil
	file_community_v1_community_proto_depIdxs = nil
}
