syntax = "proto3";

package dm.v1;

option go_package = "github.com/sudo-odner/minor-shared/pkg/pb/dm/v1;dmv1";

service DMService {
  rpc FetchPermission(FetchPermissionRequest) returns (FetchPermissionResponse);
  rpc FetchMembers(FetchMembersRequest) returns (FetchMembersResponse);
}

message FetchPermissionRequest {
  bytes user_id = 1;
  bytes channel_id = 2;
}

message FetchPermissionResponse {
  uint64 permission_mask = 1;
}

message FetchMembersRequest {
  bytes channel_id = 1;
}

message FetchMembersResponse {
  repeated bytes user_ids = 1;
}
