// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: guild/v1/guild.proto

package guildv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CanWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteRequest) Reset() {
	*x = CanWriteRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteRequest) ProtoMessage() {}

func (x *CanWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteRequest.ProtoReflect.Descriptor instead.
func (*CanWriteRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{0}
}

func (x *CanWriteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CanWriteRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type CanWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAllowed     bool                   `protobuf:"varint,1,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanWriteResponse) Reset() {
	*x = CanWriteResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanWriteResponse) ProtoMessage() {}

func (x *CanWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanWriteResponse.ProtoReflect.Descriptor instead.
func (*CanWriteResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{1}
}

func (x *CanWriteResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

type CanReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanReadRequest) Reset() {
	*x = CanReadRequest{}
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReadRequest) ProtoMessage() {}

func (x *CanReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanReadRequest.ProtoReflect.Descriptor instead.
func (*CanReadRequest) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{2}
}

func (x *CanReadRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CanReadRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type CanReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsAllowed     bool                   `protobuf:"varint,1,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanReadResponse) Reset() {
	*x = CanReadResponse{}
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanReadResponse) ProtoMessage() {}

func (x *CanReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_guild_v1_guild_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanReadResponse.ProtoReflect.Descriptor instead.
func (*CanReadResponse) Descriptor() ([]byte, []int) {
	return file_guild_v1_guild_proto_rawDescGZIP(), []int{3}
}

func (x *CanReadResponse) GetIsAllowed() bool {
	if x != nil {
		return x.IsAllowed
	}
	return false
}

var File_guild_v1_guild_proto protoreflect.FileDescriptor

const file_guild_v1_guild_proto_rawDesc = "" +
	"\n" +
	"\x14guild/v1/guild.proto\x12\bguild.v1\"I\n" +
	"\x0fCanWriteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"1\n" +
	"\x10CanWriteResponse\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x01 \x01(\bR\tisAllowed\"H\n" +
	"\x0eCanReadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"0\n" +
	"\x0fCanReadResponse\x12\x1d\n" +
	"\n" +
	"is_allowed\x18\x01 \x01(\bR\tisAllowed2\x91\x01\n" +
	"\fGuildService\x12A\n" +
	"\bCanWrite\x12\x19.guild.v1.CanWriteRequest\x1a\x1a.guild.v1.CanWriteResponse\x12>\n" +
	"\aCanRead\x12\x18.guild.v1.CanReadRequest\x1a\x19.guild.v1.CanReadResponseB\x9f\x01\n" +
	"\fcom.guild.v1B\n" +
	"GuildProtoP\x01ZBgithub.com/sudo-odner/minor/backend/shared/pkg/pb/guild/v1;guildv1\xa2\x02\x03GXX\xaa\x02\bGuild.V1\xca\x02\bGuild\\V1\xe2\x02\x14Guild\\V1\\GPBMetadata\xea\x02\tGuild::V1b\x06proto3"

var (
	file_guild_v1_guild_proto_rawDescOnce sync.Once
	file_guild_v1_guild_proto_rawDescData []byte
)

func file_guild_v1_guild_proto_rawDescGZIP() []byte {
	file_guild_v1_guild_proto_rawDescOnce.Do(func() {
		file_guild_v1_guild_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)))
	})
	return file_guild_v1_guild_proto_rawDescData
}

var file_guild_v1_guild_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_guild_v1_guild_proto_goTypes = []any{
	(*CanWriteRequest)(nil),  // 0: guild.v1.CanWriteRequest
	(*CanWriteResponse)(nil), // 1: guild.v1.CanWriteResponse
	(*CanReadRequest)(nil),   // 2: guild.v1.CanReadRequest
	(*CanReadResponse)(nil),  // 3: guild.v1.CanReadResponse
}
var file_guild_v1_guild_proto_depIdxs = []int32{
	0, // 0: guild.v1.GuildService.CanWrite:input_type -> guild.v1.CanWriteRequest
	2, // 1: guild.v1.GuildService.CanRead:input_type -> guild.v1.CanReadRequest
	1, // 2: guild.v1.GuildService.CanWrite:output_type -> guild.v1.CanWriteResponse
	3, // 3: guild.v1.GuildService.CanRead:output_type -> guild.v1.CanReadResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_guild_v1_guild_proto_init() }
func file_guild_v1_guild_proto_init() {
	if File_guild_v1_guild_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_guild_v1_guild_proto_rawDesc), len(file_guild_v1_guild_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_guild_v1_guild_proto_goTypes,
		DependencyIndexes: file_guild_v1_guild_proto_depIdxs,
		MessageInfos:      file_guild_v1_guild_proto_msgTypes,
	}.Build()
	File_guild_v1_guild_proto = out.File
	file_guild_v1_guild_proto_goTypes = nil
	file_guild_v1_guild_proto_depIdxs = nil
}
