// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: dm/v1/dm.proto

package dmv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        []byte                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     []byte                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPermissionRequest) Reset() {
	*x = FetchPermissionRequest{}
	mi := &file_dm_v1_dm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionRequest) ProtoMessage() {}

func (x *FetchPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dm_v1_dm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionRequest.ProtoReflect.Descriptor instead.
func (*FetchPermissionRequest) Descriptor() ([]byte, []int) {
	return file_dm_v1_dm_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPermissionRequest) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *FetchPermissionRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type FetchPermissionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionMask uint64                 `protobuf:"varint,1,opt,name=permission_mask,json=permissionMask,proto3" json:"permission_mask,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchPermissionResponse) Reset() {
	*x = FetchPermissionResponse{}
	mi := &file_dm_v1_dm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionResponse) ProtoMessage() {}

func (x *FetchPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dm_v1_dm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionResponse.ProtoReflect.Descriptor instead.
func (*FetchPermissionResponse) Descriptor() ([]byte, []int) {
	return file_dm_v1_dm_proto_rawDescGZIP(), []int{1}
}

func (x *FetchPermissionResponse) GetPermissionMask() uint64 {
	if x != nil {
		return x.PermissionMask
	}
	return 0
}

type FetchMembersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     []byte                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMembersRequest) Reset() {
	*x = FetchMembersRequest{}
	mi := &file_dm_v1_dm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMembersRequest) ProtoMessage() {}

func (x *FetchMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dm_v1_dm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMembersRequest.ProtoReflect.Descriptor instead.
func (*FetchMembersRequest) Descriptor() ([]byte, []int) {
	return file_dm_v1_dm_proto_rawDescGZIP(), []int{2}
}

func (x *FetchMembersRequest) GetChannelId() []byte {
	if x != nil {
		return x.ChannelId
	}
	return nil
}

type FetchMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       [][]byte               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMembersResponse) Reset() {
	*x = FetchMembersResponse{}
	mi := &file_dm_v1_dm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMembersResponse) ProtoMessage() {}

func (x *FetchMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dm_v1_dm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMembersResponse.ProtoReflect.Descriptor instead.
func (*FetchMembersResponse) Descriptor() ([]byte, []int) {
	return file_dm_v1_dm_proto_rawDescGZIP(), []int{3}
}

func (x *FetchMembersResponse) GetUserIds() [][]byte {
	if x != nil {
		return x.UserIds
	}
	return nil
}

var File_dm_v1_dm_proto protoreflect.FileDescriptor

const file_dm_v1_dm_proto_rawDesc = "" +
	"\n" +
	"\x0edm/v1/dm.proto\x12\x05dm.v1\"P\n" +
	"\x16FetchPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\fR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\fR\tchannelId\"B\n" +
	"\x17FetchPermissionResponse\x12'\n" +
	"\x0fpermission_mask\x18\x01 \x01(\x04R\x0epermissionMask\"4\n" +
	"\x13FetchMembersRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\fR\tchannelId\"1\n" +
	"\x14FetchMembersResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\fR\auserIds2\xa6\x01\n" +
	"\tDMService\x12P\n" +
	"\x0fFetchPermission\x12\x1d.dm.v1.FetchPermissionRequest\x1a\x1e.dm.v1.FetchPermissionResponse\x12G\n" +
	"\fFetchMembers\x12\x1a.dm.v1.FetchMembersRequest\x1a\x1b.dm.v1.FetchMembersResponseB6Z4github.com/sudo-odner/minor-shared/pkg/pb/dm/v1;dmv1b\x06proto3"

var (
	file_dm_v1_dm_proto_rawDescOnce sync.Once
	file_dm_v1_dm_proto_rawDescData []byte
)

func file_dm_v1_dm_proto_rawDescGZIP() []byte {
	file_dm_v1_dm_proto_rawDescOnce.Do(func() {
		file_dm_v1_dm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dm_v1_dm_proto_rawDesc), len(file_dm_v1_dm_proto_rawDesc)))
	})
	return file_dm_v1_dm_proto_rawDescData
}

var file_dm_v1_dm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dm_v1_dm_proto_goTypes = []any{
	(*FetchPermissionRequest)(nil),  // 0: dm.v1.FetchPermissionRequest
	(*FetchPermissionResponse)(nil), // 1: dm.v1.FetchPermissionResponse
	(*FetchMembersRequest)(nil),     // 2: dm.v1.FetchMembersRequest
	(*FetchMembersResponse)(nil),    // 3: dm.v1.FetchMembersResponse
}
var file_dm_v1_dm_proto_depIdxs = []int32{
	0, // 0: dm.v1.DMService.FetchPermission:input_type -> dm.v1.FetchPermissionRequest
	2, // 1: dm.v1.DMService.FetchMembers:input_type -> dm.v1.FetchMembersRequest
	1, // 2: dm.v1.DMService.FetchPermission:output_type -> dm.v1.FetchPermissionResponse
	3, // 3: dm.v1.DMService.FetchMembers:output_type -> dm.v1.FetchMembersResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dm_v1_dm_proto_init() }
func file_dm_v1_dm_proto_init() {
	if File_dm_v1_dm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dm_v1_dm_proto_rawDesc), len(file_dm_v1_dm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dm_v1_dm_proto_goTypes,
		DependencyIndexes: file_dm_v1_dm_proto_depIdxs,
		MessageInfos:      file_dm_v1_dm_proto_msgTypes,
	}.Build()
	File_dm_v1_dm_proto = out.File
	file_dm_v1_dm_proto_goTypes = nil
	file_dm_v1_dm_proto_depIdxs = nil
}
