// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: dm/v1/dm.proto

package dmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DMService_FetchPermission_FullMethodName = "/dm.v1.DMService/FetchPermission"
)

// DMServiceClient is the client API for DMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DMServiceClient interface {
	FetchPermission(ctx context.Context, in *FetchPermissionRequest, opts ...grpc.CallOption) (*FetchPermissionResponse, error)
}

type dMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDMServiceClient(cc grpc.ClientConnInterface) DMServiceClient {
	return &dMServiceClient{cc}
}

func (c *dMServiceClient) FetchPermission(ctx context.Context, in *FetchPermissionRequest, opts ...grpc.CallOption) (*FetchPermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPermissionResponse)
	err := c.cc.Invoke(ctx, DMService_FetchPermission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DMServiceServer is the server API for DMService service.
// All implementations must embed UnimplementedDMServiceServer
// for forward compatibility.
type DMServiceServer interface {
	FetchPermission(context.Context, *FetchPermissionRequest) (*FetchPermissionResponse, error)
	mustEmbedUnimplementedDMServiceServer()
}

// UnimplementedDMServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDMServiceServer struct{}

func (UnimplementedDMServiceServer) FetchPermission(context.Context, *FetchPermissionRequest) (*FetchPermissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPermission not implemented")
}
func (UnimplementedDMServiceServer) mustEmbedUnimplementedDMServiceServer() {}
func (UnimplementedDMServiceServer) testEmbeddedByValue()                   {}

// UnsafeDMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DMServiceServer will
// result in compilation errors.
type UnsafeDMServiceServer interface {
	mustEmbedUnimplementedDMServiceServer()
}

func RegisterDMServiceServer(s grpc.ServiceRegistrar, srv DMServiceServer) {
	// If the following call panics, it indicates UnimplementedDMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DMService_ServiceDesc, srv)
}

func _DMService_FetchPermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DMServiceServer).FetchPermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DMService_FetchPermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DMServiceServer).FetchPermission(ctx, req.(*FetchPermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DMService_ServiceDesc is the grpc.ServiceDesc for DMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dm.v1.DMService",
	HandlerType: (*DMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchPermission",
			Handler:    _DMService_FetchPermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dm/v1/dm.proto",
}
