// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: relationship/v1/relationship.proto

package relationshipv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchPermissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchPermissionRequest) Reset() {
	*x = FetchPermissionRequest{}
	mi := &file_relationship_v1_relationship_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionRequest) ProtoMessage() {}

func (x *FetchPermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_v1_relationship_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionRequest.ProtoReflect.Descriptor instead.
func (*FetchPermissionRequest) Descriptor() ([]byte, []int) {
	return file_relationship_v1_relationship_proto_rawDescGZIP(), []int{0}
}

func (x *FetchPermissionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FetchPermissionRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

type FetchPermissionResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PermissionMask uint64                 `protobuf:"varint,1,opt,name=permission_mask,json=permissionMask,proto3" json:"permission_mask,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchPermissionResponse) Reset() {
	*x = FetchPermissionResponse{}
	mi := &file_relationship_v1_relationship_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPermissionResponse) ProtoMessage() {}

func (x *FetchPermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_relationship_v1_relationship_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPermissionResponse.ProtoReflect.Descriptor instead.
func (*FetchPermissionResponse) Descriptor() ([]byte, []int) {
	return file_relationship_v1_relationship_proto_rawDescGZIP(), []int{1}
}

func (x *FetchPermissionResponse) GetPermissionMask() uint64 {
	if x != nil {
		return x.PermissionMask
	}
	return 0
}

var File_relationship_v1_relationship_proto protoreflect.FileDescriptor

const file_relationship_v1_relationship_proto_rawDesc = "" +
	"\n" +
	"\"relationship/v1/relationship.proto\x12\x0frelationship.v1\"P\n" +
	"\x16FetchPermissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"B\n" +
	"\x17FetchPermissionResponse\x12'\n" +
	"\x0fpermission_mask\x18\x01 \x01(\x04R\x0epermissionMask2{\n" +
	"\x13RelationshipService\x12d\n" +
	"\x0fFetchPermission\x12'.relationship.v1.FetchPermissionRequest\x1a(.relationship.v1.FetchPermissionResponseBJZHgithub.com/sudo-odner/minor-shared/pkg/pb/relationship/v1;relationshipv1b\x06proto3"

var (
	file_relationship_v1_relationship_proto_rawDescOnce sync.Once
	file_relationship_v1_relationship_proto_rawDescData []byte
)

func file_relationship_v1_relationship_proto_rawDescGZIP() []byte {
	file_relationship_v1_relationship_proto_rawDescOnce.Do(func() {
		file_relationship_v1_relationship_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_relationship_v1_relationship_proto_rawDesc), len(file_relationship_v1_relationship_proto_rawDesc)))
	})
	return file_relationship_v1_relationship_proto_rawDescData
}

var file_relationship_v1_relationship_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_relationship_v1_relationship_proto_goTypes = []any{
	(*FetchPermissionRequest)(nil),  // 0: relationship.v1.FetchPermissionRequest
	(*FetchPermissionResponse)(nil), // 1: relationship.v1.FetchPermissionResponse
}
var file_relationship_v1_relationship_proto_depIdxs = []int32{
	0, // 0: relationship.v1.RelationshipService.FetchPermission:input_type -> relationship.v1.FetchPermissionRequest
	1, // 1: relationship.v1.RelationshipService.FetchPermission:output_type -> relationship.v1.FetchPermissionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_relationship_v1_relationship_proto_init() }
func file_relationship_v1_relationship_proto_init() {
	if File_relationship_v1_relationship_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_relationship_v1_relationship_proto_rawDesc), len(file_relationship_v1_relationship_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_relationship_v1_relationship_proto_goTypes,
		DependencyIndexes: file_relationship_v1_relationship_proto_depIdxs,
		MessageInfos:      file_relationship_v1_relationship_proto_msgTypes,
	}.Build()
	File_relationship_v1_relationship_proto = out.File
	file_relationship_v1_relationship_proto_goTypes = nil
	file_relationship_v1_relationship_proto_depIdxs = nil
}
